package com.ffcs.ctsw.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISMServicePortType", targetNamespace = "http://webservice.ctsw.ffcs.com")
public interface ISMServicePortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in4
	 * @param in3
	 * @param in0
	 * @param in5
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://webservice.ctsw.ffcs.com")
	@RequestWrapper(localName = "inceptSMContent", targetNamespace = "http://webservice.ctsw.ffcs.com", className = "com.ffcs.ctsw.webservice.InceptSMContent")
	@ResponseWrapper(localName = "inceptSMContentResponse", targetNamespace = "http://webservice.ctsw.ffcs.com", className = "com.ffcs.ctsw.webservice.InceptSMContentResponse")
	public int inceptSMContent(
			@WebParam(name = "in0", targetNamespace = "http://webservice.ctsw.ffcs.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://webservice.ctsw.ffcs.com") String in1,
			@WebParam(name = "in2", targetNamespace = "http://webservice.ctsw.ffcs.com") String in2,
			@WebParam(name = "in3", targetNamespace = "http://webservice.ctsw.ffcs.com") String in3,
			@WebParam(name = "in4", targetNamespace = "http://webservice.ctsw.ffcs.com") String in4,
			@WebParam(name = "in5", targetNamespace = "http://webservice.ctsw.ffcs.com") String in5);

}
